"""infermap core dataclasses."""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

import yaml

logger = logging.getLogger("infermap")
VALID_DTYPES = {"string", "integer", "float", "boolean", "date", "datetime"}


@dataclass
class FieldInfo:
    name: str
    dtype: str = "string"
    sample_values: list[str] = field(default_factory=list)
    null_rate: float = 0.0
    unique_rate: float = 0.0
    value_count: int = 0
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        if self.dtype not in VALID_DTYPES:
            self.dtype = "string"


@dataclass
class SchemaInfo:
    fields: list[FieldInfo]
    source_name: str = ""
    required_fields: list[str] = field(default_factory=list)


@dataclass
class ScorerResult:
    score: float
    reasoning: str

    def __post_init__(self):
        self.score = max(0.0, min(1.0, self.score))


@dataclass
class FieldMapping:
    source: str
    target: str
    confidence: float
    breakdown: dict[str, ScorerResult] = field(default_factory=dict)
    reasoning: str = ""


@dataclass
class MapResult:
    mappings: list[FieldMapping]
    unmapped_source: list[str] = field(default_factory=list)
    unmapped_target: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
    score_matrix: dict[str, dict[str, float]] | None = None

    def report(self) -> dict:
        return {
            "mappings": [
                {
                    "source": m.source,
                    "target": m.target,
                    "confidence": round(m.confidence, 3),
                    "breakdown": {
                        name: {"score": round(r.score, 3), "reasoning": r.reasoning}
                        for name, r in m.breakdown.items()
                    },
                    "reasoning": m.reasoning,
                }
                for m in self.mappings
            ],
            "unmapped_source": self.unmapped_source,
            "unmapped_target": self.unmapped_target,
            "warnings": self.warnings,
        }

    def apply(self, df):
        from .errors import ApplyError

        is_pandas = hasattr(df, "iloc")
        col_set = set(df.columns)
        missing = [m.source for m in self.mappings if m.source not in col_set]
        if missing:
            raise ApplyError(f"Source columns missing from DataFrame: {missing}")
        if is_pandas:
            return df.rename(columns={m.source: m.target for m in self.mappings})
        return df.rename({m.source: m.target for m in self.mappings})

    def to_config(self, path: str) -> None:
        data = {
            "version": "1",
            "mappings": [
                {"source": m.source, "target": m.target, "confidence": round(m.confidence, 3)}
                for m in self.mappings
            ],
            "unmapped_source": self.unmapped_source,
            "unmapped_target": self.unmapped_target,
        }
        with open(path, "w") as f:
            f.write("# Generated by infermap\n")
            yaml.dump(data, f, default_flow_style=False, sort_keys=False)

    def to_json(self) -> str:
        return json.dumps(self.report(), indent=2)
